kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_token
    repo: awerv/drone_pushover
    tags: latest
    when:
      branch: master
      event: push